#!/usr/bin/env python3
import time
import socketserver

class ChallengeHandler(socketserver.BaseRequestHandler):
    
    def send(self, text):
        self.request.sendall(text.encode())

    def recv(self):
        try:
            return self.request.recv(1024).decode().strip().lower()
        except:
            return ""

    def win(self):
        self.send("\n[$$$] CRITICAL OVERRIDE: Bypassing Security...\n")
        time.sleep(0.5)
        
        # Look for the physical flag file generated by start.sh
        try:
            with open('/flag', 'r') as f:
                flag = f.read().strip()
        except Exception as e:
            flag = f"flag{{file_read_error:_{e}}}"
        
        self.send("[+] ARTIFACT DECRYPTED. FLAG RECOVERED:\n")
        self.send(f"[+] {flag}\n\n")
        return False

    def safe_action(self):
        self.send("\n[SYS] You hold the artifact. It hums safely.\n")

    def draw_map(self):
        self.send("\033[2J\033[H")
        self.send("=== PYTHON DUNGEON CRAWLER ===\n")
        self.send("[*] Artifact  [T] Trash  [E] Editor  [A] Altar\n\n")
        
        for row in self.map_grid:
            self.send("".join(row) + "\n")
            
        self.send("\nMove (w/a/s/d): ")

    def process_tile(self):
        current_tile = self.map_grid[self.py][self.px]

        if current_tile == '*':
            if self.inventory_ptr is None and len(self.free_list) > 0:
                chunk_idx = self.free_list.pop(0)
                self.heap[chunk_idx] = "safe_action()" 
                self.inventory_ptr = chunk_idx 
                self.send("\n[+] Picked up the Artifact! (Allocated chunk)\n")
            self.map_grid[self.py][self.px] = '.'

        elif current_tile == 'T':
            if self.inventory_ptr is not None:
                self.free_list.insert(0, self.inventory_ptr)
                self.heap[self.inventory_ptr] = None
                self.send("\n[-] Threw the Artifact in the trash! (Chunk freed)\n")

        elif current_tile == 'E':
            self.send("\n[?] Write a note (max 32 chars): ")
            note = self.recv()
            
            if len(self.free_list) > 0:
                chunk_idx = self.free_list.pop(0) 
                self.heap[chunk_idx] = note[:32] 
                self.send("\n[+] Note saved in heap.\n")

        elif current_tile == 'A':
            if self.inventory_ptr is not None:
                self.send("\n[!] Placing artifact on Altar...\n")
                try:
                    payload = self.heap[self.inventory_ptr]
                    if payload:
                        exec_globals = {
                            '__builtins__': __builtins__,
                            'win': self.win,
                            'safe_action': self.safe_action
                        }
                        exec(payload, exec_globals) 
                    else:
                        self.send("[-] Artifact is empty.\n")
                except Exception as e:
                    self.send(f"[-] Execution failed: {e}\n")
            else:
                self.send("\n[-] You have nothing to place here.\n")
                
        time.sleep(1)
        return True

    def handle(self):
        self.heap = [None] * 10
        self.free_list = [0, 1, 2, 3]
        self.inventory_ptr = None
        self.px, self.py = 1, 1
        
        self.map_grid = [
            list("#######"),
            list("#@...*#"),
            list("#.....#"),
            list("#..A..#"),
            list("#.....#"),
            list("#T...E#"),
            list("#######")
        ]

        running = True
        while running:
            self.draw_map()
            move = self.recv()
            
            if not move:
                break
            
            nx, ny = self.px, self.py
            if move == 'w': ny -= 1
            elif move == 's': ny += 1
            elif move == 'a': nx -= 1
            elif move == 'd': nx += 1

            if self.map_grid[ny][nx] != '#':
                self.map_grid[self.py][self.px] = '.' 
                self.px, self.py = nx, ny
                running = self.process_tile() 
                self.map_grid[self.py][self.px] = '@' 

if __name__ == "__main__":
    HOST, PORT = "0.0.0.0", 9993
    server = socketserver.ThreadingTCPServer((HOST, PORT), ChallengeHandler)
    server.allow_reuse_address = True
    print(f"[*] Native Python TCP Server Listening on {HOST}:{PORT}")
    server.serve_forever()
